credentials:
  usernames:
    admin:
      name: "Admin User"
      password: "admin123"  # Change this!
    doctor1:
      name: "Dr. Smith"
      password: "doctorpassword"
cookie:
  name: "alzheimers_app"
  key: "some_random_secret_key"
  expiry_days: 7